# Generated by Django 4.2.5 on 2023-10-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useriplocation',
            name='postal',
        ),
    ]
